### ISSUE TITLE
Any plans to make indentation configurable?

### ISSUE THREAD

**Issue by infotexture** [jason-fox/fox.jason.pretty-dita#1]
💡 Interesting idea to implement a pretty-printer as an OT plug-in. 🤔 

I appreciate the concept of an [opinionated code formatter](https://prettier.io), but I find the results here a bit surprising, as most elements are indented with 3 spaces, but things like paragraph contents by 4.

I'm also seeing unexpected results for unordered lists within paragraphs, and varying line lengths.

Here's a sample from the [preprocess-metadata.dita](https://github.com/dita-ot/docs/blob/develop/reference/preprocess-metadata.dita) file in the DITA-OT docs, which was already formatted consistently with oXygen's **Format & Indent** command:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  This file is part of the DITA Open Toolkit project. See the accompanying LICENSE file for applicable license.  -->
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
<concept id="preprocess-metadata" xml:lang="en-US">
   <title>Move metadata (move-meta-entries) and pull content into maps (mappull) </title>
   <shortdesc>The <codeph>move-meta-entries</codeph> step pushes metadata back and forth between maps and topics. For
    example, index entries and copyrights in the map are pushed into affected topics, so that the topics can be
    processed later in isolation while retaining all relevant metadata. This step is implemented in Java.
   </shortdesc>
   <conbody>
      <note>As of DITA-OT 2.2, the <codeph>move-meta-entries</codeph> and <codeph>mappull</codeph> steps have been merged.
      The <codeph>mappull</codeph> step has been moved into <codeph>move-meta-entries</codeph>.
      </note>
      <section>
         <p>
             The <codeph>mappull</codeph> step pulls content from referenced
             topics into maps, and then cascades data within maps. This step is implemented in XSLT. 
        </p>
         <p>
                   The <codeph>mappull</codeph> step makes the following changes to the
                   DITA map:  <ul>                <li>Titles are pulled from referenced DITA
                   topics. Unless the  <xmlatt>locktitle</xmlatt> attribute is set to "yes", the
                   pulled titles replace the navigation titles specified on the <xmlelement>topicref</xmlelement>
                   elements. 
              </li>

               <!-- ⋮ more list items -->

</ul>
              
        </p>
      </section>
   </conbody>
</concept>
```

It seems that closing tags for some elements (like `</shortdesc>`) align with the opening angle brackets of their opening counterparts as usual, but others (like `</p>`) appear "outdented" to align with the element name.

Might be good to document these choices so people know what to expect when formatting a large codebase, and consider options (transtypes?) that would allow users to influence the results.

**Comment by jason-fox** [comment]
@infotexture - I have fixed the markup on _lists-inside-paragraphs_  and added a new test - https://github.com/jason-fox/fox.jason.pretty-dita/tree/master/test/embedded-block

(compare `topic.xml` and `expectation.xml` to see the formatting for example)

For configuration, the key lines are as follows:

```xml
<!-- Block elements requiring a new line are listed here -->
 <xsl:when test="self::p|self::shortdesc|self::li|self::note">
```

And

```xml
<!-- Inline elements are listed here -->
<xsl:template match="b|i|sup|sub|codeph|xref|xmlatt|xmlelement|ph">
```

All other elements are considered to be  simple block level elements without a leading carriage return.

Are there other  DITA elements which should be added to either list?

**Comment by jason-fox** [comment]
I've just added command-line configurability for tabs vs spaces and the number of indents.

see [Release 1.1.0](https://github.com/jason-fox/fox.jason.pretty-dita/releases/tag/v1.1.0)

**Comment by jason-fox** [comment]
Additional command line parameters supporting pragma operations, print width and formatting of a single file have now been added. The transform is now fully configurable.

see [Release 1.2.0](https://github.com/jason-fox/fox.jason.pretty-dita/releases/tag/v1.2.0)

**Comment by infotexture** [comment]
Sorry I didn't have time to test this earlier, but the results with the new 1.2.0 version look much better. 👍 

The additional configuration options, single-file formatting, pragma support, and updated docs should make this much more versatile for everyday use.

Thanks for your work. 🙏
