### ISSUE TITLE
Does not resolves relative topic dirs correctly 

### ISSUE THREAD

**Issue by hcw70** [jason-fox/fox.jason.pretty-dita#3]
Anogther one i found:

I am using relative paths in our dita map like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
  <title>DMI Integration Handbook</title>
  <topichead navtitle="Introduction">
    <topicref href="topics/intro-audience.dita"/>
    <topicref href="../../src-cmake/generic-dmi/doc/topics/intro/dmi-intro-hw.dita"/>
  </topichead>
</map>

```

When i run dita-prettty like this:

`hcw@nvidion:~/work/Deuta/dmi-projects/05-Implementation/build-x86-debug$ ./src-cmake/generic-dmi/doc/dita-plugins/dita-ot-3.3.4/src/dita-dl/bin/dita -f pretty-dita -i ../doc/IntegrationHandbook/DMI_Integration_Handbook.ditamap
`

it only picks up the first dita topic, but does not touch the second one.

Looks like the tool is evaluating the relative path statement not relative to the ditamap (as it should be, at least as DITA-OT also does it).

**Comment by jason-fox** [comment]
I'm guessing `dmi-intro-hw.dita` may be using one of the missing XMLCatalog DTDs which were added to fix #2 

Could you try re-installing with the latest change and tell me if it now works or not?

```console
dita -uninstall fox.jason.pretty-dita
dita -install https://github.com/jason-fox/fox.jason.pretty-dita/archive/master.zip
```

If it doesn't, could you add the content of `dmi-intro-hw.dita` to the issue?

**Comment by hcw70** [comment]
The contents is as following (shortened):

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
<concept id="concept_dmi_intro_hw">
 <title>Hardware of the DMI</title>
 <shortdesc>The hardware components present in the <abbreviated-form keyref="gloss-dmi"/>.</shortdesc>
 <conbody>
...
</conbody>
</concept>
```
So IMHO nothing special but a simple dita concept.

I will give 1.3.1 a try.

**Comment by hcw70** [comment]
So also the 1.3.1 does not pick up any topics from the "../../src-cmake/generic-dmi" folders...

**Comment by jason-fox** [comment]
Looking at your command I understand why the transform isn't working. Unlike ordinary transforms, it doesn't rely on the `*.ditamap` to read the files to tidy. I think however with the bug fixes, you should however be able to run pretty-dita over a single **directory** directly  as shown:

```console
dita-ot-3.3.4/bin/dita -f pretty-dita -i src-cmake/generic-dmi/doc/topics
```
This would tidy the files under that **directory**

**Comment by hcw70** [comment]
Ah, ok, as reading your doc:
```
To prettify DITA files for a document, use the pretty-dita transform, set the --input parameter to point to a *.ditamap file:

PATH_TO_DITA_OT/bin/dita -f pretty-dita -i document.ditamap

```
i had the impression that it should read the ditamap and pretty-print all mentioned topics....
