### ISSUE TITLE
Inserts linefeed in codeblock

### ISSUE THREAD

**Issue by hcw70** [jason-fox/fox.jason.pretty-dita#8]
Another one... 8->

When pretty-printing the following, a newline is inserted after the "cd" before the "abbreviated-form".

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE task PUBLIC "-//OASIS//DTD DITA Task//EN" "task.dtd">
<task id="dialog-add-new-language">
    <title>Extend...</title>
    <shortdesc>
       Allow...
    </shortdesc>
    <taskbody>
        <steps>
            <step>
                <cmd>Regenerate the configuration files.</cmd>
                <stepxmp>
                    <codeblock>$ cd <abbreviated-form keyref="gloss-cfgdir"/>/build
$ make
                    </codeblock>
                </stepxmp>
            </step>
        </steps>
    </taskbody>
</task>
```

**Comment by jason-fox** [comment]
It is assumed that `<codeblock>` will usually contain either a single reference or text only.
Block elements will be formatted such as `<coderef>` will be indented.

`<abbreviated-form>`, `<markup>` and `<text>` were not listed as inline elements, so were treated as block elements. To treat additional elements as inline, just add a [section](https://github.com/jason-fox/fox.jason.pretty-dita/blob/master/Customization/xsl/prettier-rules.xsl#L82-L85) as shown.
